#!/usr/bin/python3
# -*- coding: utf-8 -*-

import socketserver
import sys
import os
from xml.sax import make_parser
from xml.sax.handler import ContentHandler


class UserAgent(ContentHandler):
    """Sacar puertos e ips. """
    def __init__(self):
        """Diccionario"""
        self.diccConfig = {"account":["username", "passwd"],
                              "uaserver": ["ip","puerto"],
                              "rtpaudio":["puerto"],
                              "regproxy":["ip","puerto"],
                              "log": ["path"],
                              "audio": ["path"]}
        self.Config = {}

    def startElement(self, name, attrs):

        #print(self.Config)
        if name in self.diccConfig:
            print("hola")
            for info in self.diccConfig[name]:
                self.Config[name + '_' + info] = attrs.get(info, "")

    def get_tags(self):
        return self.Config


if __name__ == "__main__":

    parser = make_parser()
    sHandler = UserAgent()
    parser.setContentHandler(sHandler)
    parser.parse(open('ua2.xml'))
    Config = sHandler.get_tags()
    print(Config['account_username'])

#UA server

    if len(sys.argv) == 2:
        ua = sys.argv[1]
        Config[]
    else:
        sys.exit("Usage: python uaserver.py config")
